# -*- coding: utf-8 -*-
"""Custom Title Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVM_3FipJevLZGgm-dXZLiK32rwfy5Bf
"""

def title(input_string):
  array = input_string.split(" ")
  for i in array:
   print("".join(i.capitalize()),end=" ")
  print(" ")

title("Hello this is zahoor")

